tasks:
  - init: |
      # Install Google Chrome
      sudo apt-get update
      sudo apt-get install -y wget unzip
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
      rm google-chrome-stable_current_amd64.deb
      google-chrome --version
      pip install --upgrade pip
      pip install -r requirements.txt